# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/blockWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_blockWidget(object):
    def setupUi(self, blockWidget):
        blockWidget.setObjectName("blockWidget")
        blockWidget.resize(544, 146)
        blockWidget.setMinimumSize(QtCore.QSize(0, 50))
        blockWidget.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.verticalLayout = QtWidgets.QVBoxLayout(blockWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.blockName = QtWidgets.QLabel(blockWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockName.sizePolicy().hasHeightForWidth())
        self.blockName.setSizePolicy(sizePolicy)
        self.blockName.setMinimumSize(QtCore.QSize(0, 25))
        self.blockName.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.blockName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.blockName.setStyleSheet("font-weight: bold;")
        self.blockName.setTextFormat(QtCore.Qt.PlainText)
        self.blockName.setScaledContents(True)
        self.blockName.setAlignment(QtCore.Qt.AlignCenter)
        self.blockName.setWordWrap(True)
        self.blockName.setIndent(-1)
        self.blockName.setObjectName("blockName")
        self.verticalLayout.addWidget(self.blockName)

        self.retranslateUi(blockWidget)
        QtCore.QMetaObject.connectSlotsByName(blockWidget)

    def retranslateUi(self, blockWidget):
        _translate = QtCore.QCoreApplication.translate
        blockWidget.setWindowTitle(_translate("blockWidget", "Form"))
        self.blockName.setText(_translate("blockWidget", "fasasfasssssssssssssasfasasfasssssssssssssasfasasfasssssssssssssasfasasfsssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasf asssssssssssasfasasfasssssssssssssasf asasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssssssasfasasfasssssssssssasfasasfasssssssssss ssasfasasfassasssssssssssssasfasa sfa sssssssssssssasfasasfasssssssssssssas"))
