# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/examPairWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_examPair(object):
    def setupUi(self, examPair):
        examPair.setObjectName("examPair")
        examPair.resize(635, 58)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(examPair)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(examPair)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.examName = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examName.sizePolicy().hasHeightForWidth())
        self.examName.setSizePolicy(sizePolicy)
        self.examName.setMinimumSize(QtCore.QSize(350, 0))
        self.examName.setMaximumSize(QtCore.QSize(350, 16777215))
        self.examName.setWordWrap(True)
        self.examName.setObjectName("examName")
        self.horizontalLayout.addWidget(self.examName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.examChoose = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examChoose.sizePolicy().hasHeightForWidth())
        self.examChoose.setSizePolicy(sizePolicy)
        self.examChoose.setMaximumSize(QtCore.QSize(400, 16777215))
        self.examChoose.setObjectName("examChoose")
        self.horizontalLayout.addWidget(self.examChoose)
        self.horizontalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(examPair)
        QtCore.QMetaObject.connectSlotsByName(examPair)

    def retranslateUi(self, examPair):
        _translate = QtCore.QCoreApplication.translate
        examPair.setWindowTitle(_translate("examPair", "Form"))
        self.examName.setText(_translate("examPair", "TextLabel"))
