# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'languageChoice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_languageChoice(object):
    def setupUi(self, languageChoice):
        languageChoice.setObjectName("languageChoice")
        languageChoice.resize(786, 513)
        self.verticalLayout = QtWidgets.QVBoxLayout(languageChoice)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(languageChoice)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(languageChoice)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(languageChoice)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(languageChoice)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 766, 423))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetsLayout = QtWidgets.QVBoxLayout()
        self.widgetsLayout.setObjectName("widgetsLayout")
        self.verticalLayout_2.addLayout(self.widgetsLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(languageChoice)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(languageChoice)
        QtCore.QMetaObject.connectSlotsByName(languageChoice)

    def retranslateUi(self, languageChoice):
        _translate = QtCore.QCoreApplication.translate
        languageChoice.setWindowTitle(_translate("languageChoice", "Form"))
        self.label.setText(_translate("languageChoice", "Студент"))
        self.label_2.setText(_translate("languageChoice", "Язык обучения"))
        self.label_3.setText(_translate("languageChoice", "Язык защиты"))
        self.pushButton.setText(_translate("languageChoice", "Далее"))
